version: '3.8'
services:

  db:
    container_name: weather-db
    image: postgres:10.4
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=weatherDB
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready'"]

  app:
    container_name: weather-app
    env_file:
      - .env
    build: ./app/
    depends_on:
      db:
        condition: service_healthy

